# TinyEngine .YAML Direct-To-Struct Test File
# for Easy Configuration Loading

# Basic Types
integer: 25
float: 4
double: 0.25
char: 'z'
string: "test string"

# Structs and Nested Structs

StructA:
  a: 1
  b: 2.6
  c: 4
  d: 2

StructB:
  c: 'c'
  A:
    a: 15
    g: 5

StructC:
  b:
    c: 'c'
    A: 2
  g:
    g: 1

vector: 
  - 1
  - 54
  - 2
  - 56
  - 71

sset:
  - a
  - b
  - c
  - d
  - 1
  - test 

iset:
  - 1
  - 2
  - 3
  - 4
  - 5

iimap:
  1: 2
  3: 4
  5: 6

ismap:
  2: ":"
  3: "~"
  4: "!!!"

simap:
  "a": 2
  "b": 4
  "test": 6