i: 25
f: 4
d: 0.25

# Test
root:
  a: 1
  b: 2.6
  c: 4
  d: 6

broot:
  c: 'c'
  A:
    a: 15
    g: 5

c:
  b:
    c: 'c'
    A: 2
  g: 7

s: "test"

vector: 
  - 1
  - 23
  - a:
      what: up
  - 56
  - 71