# TinyEngine .YAML Direct-To-Struct Test File
# for Easy Configuration Loading

# Basic Types
integer: 25
float: 4
double: 0.25
char: 'z'
string: "test string"

# Structs and Nested Structs

StructA:
  a: 1
  b: 2.6
  c: 4
  d: 2

StructB:
  c: 'c'
  A:
    a: 15
    b: stes
    d: 6
    g: 5

StructC:
  b:
    c: 1
    A:
      a: 1
      b: 1
      d: 1
  g: 1

# Arrays

float_array:
  - 0.5
  - 0.25
  - 0.75
  - 1.0
  - 2.0

struct_array:
  - 
    a: 'a'
  - 
    a: 'b'
  - 
    a: 'c'

# STL Containers

vector: 
  - 1
  - 54
  - 2
  - 56
  - 71

sset:
  - a
  - b
  - c
  - d
  - 1
  - test 

iset:
  - 1
  - 2
  - 3
  - 4
  - 5

iimap:
  1: 2
  3: 4
  5: 6

ismap:
  2: ":"
  3: "~"
  4: "!!!"

simap:
  "a": 2
  "b": 4
  "test": 6

vector_struct:
  v: 
    - 1
    - 54
    - 2
    - 56
    - 73
