# Arrays

float_array:
  - 0.5
  - 0.25
  - 0.75
  - 1.0
  - 2.0

integer_array:
  - 1
  - 2

multi_array:
  -
    - 1
    - 2
    - 3
  -
    - 4
    - 5
    - 6

multi_array_single:
  -
    -
      - 1
      - 2
      - 3
  -
    -
      - 4
      - 5
      - 6