# GLM Types

vec2:
  - 1
  - 2

vec3:
  - 1
  - 2
  - 3

vec4:
  - 1
  - 2
  - 3
  - 4

mat2:
  -
    - 1
    - 2
  -
    - 3
    - 4

mat3:
  -
    - 1
    - 2
    - 3
  -
    - 4
    - 5
    - 6
  - 
    - 7
    - 8
    - 9

mat4:
  -
    - 1
    - 2
    - 3
    - 4
  -
    - 4
    - 5
    - 6
    - 7
  - 
    - 7
    - 8
    - 9
    - 10
  -
    - 7
    - 8
    - 9
    - 10