# stl container types

vector: 
  - 1
  - 54
  - 2
  - 56
  - 71

sset:
  - a
  - b
  - c
  - d
  - 1
  - test 

iset:
  - 1
  - 2
  - 3
  - 4
  - 5

iimap:
  1: 2
  3: 4
  5: 6

ismap:
  2: ":"
  3: "~"
  4: "!!!"

simap:
  "a": 2
  "b": 4
  "test": 6

vv:
  -
    - 1
    - 2
  -
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  - 
    - 9

miv:
  1:
    - 1
    - 2
  3:
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
  2:
    - 9