# Structs and Nested Structs

StructS:
  s: 1

StructSS:
  StructS:
    s: 2

StructA:
  a: 1
  b: 2.6

StructB:
  A:
    a: 15
    b: 1.6
  c: 'c'

StructC:
  B:
    A:
      a: 1
      b: 2
    c: c
  d: 4

StructA_arr:
  - 
    a: 1
    b: 1.5

# STL Containers

vector_struct:
  v: 
    - 1
    - 54
    - 2
    - 56
    - 73

array_struct:
  a:
    - 1
    - 2
    - 3
    - 4